### ISSUE TITLE
Update events page

### ISSUE THREAD

**Issue by slarson** [openworm/org.openworm.website#73] opened 2016-08-06 15:24 UTC
events.html is two years old now.. maybe better to remove or find a different way to represent events?  Maybe a link to the public calendar?

**Comment by MichaelCurrie** [comment] 2017-06-15 05:37
@slarson where is this public calendar?  Here is the current page: http://www.openworm.org/events.html

Perhaps you could share the email newsletter content here in this issue so that the person handling this issue will have some content to add.

**Comment by MichaelCurrie** [comment] 2017-06-26 02:53
Duplicate of https://github.com/openworm/org.openworm.website/issues/99

**Closed by MichaelCurrie** 2017-06-26 02:53 UTC
Labels: beginner, ready
